DROP TABLE IF EXISTS [customer]
GO

DROP TABLE IF EXISTS [lineitem]
GO

DROP TABLE IF EXISTS [nation]
GO

DROP TABLE IF EXISTS [orders]
GO

DROP TABLE IF EXISTS [part]
GO

DROP TABLE IF EXISTS [partsupp]
GO

DROP TABLE IF EXISTS [region]
GO

DROP TABLE IF EXISTS [supplier]
GO

CREATE TABLE partsupp
  (
     PS_PARTKEY    BIGINT NOT NULL,
     PS_SUPPKEY    BIGINT NOT NULL,
     PS_AVAILQTY   INT NOT NULL,
     PS_SUPPLYCOST DECIMAL(12, 2) NOT NULL,
     PS_COMMENT    VARCHAR(199) NOT NULL
  )
GO

CREATE TABLE part
  (
     P_PARTKEY     BIGINT NOT NULL,
     P_NAME        VARCHAR(55) NOT NULL,
     P_MFGR        CHAR(25) NOT NULL,
     P_BRAND       CHAR(10) NOT NULL,
     P_TYPE        VARCHAR(25) NOT NULL,
     P_SIZE        INT NOT NULL,
     P_CONTAINER   CHAR(10) NOT NULL,
     P_RETAILPRICE DECIMAL(12, 2) NOT NULL,
     P_COMMENT     VARCHAR(23) NOT NULL
  )
GO

CREATE TABLE customer
  (
     C_CUSTKEY    BIGINT NOT NULL,
     C_NAME       VARCHAR(25) NOT NULL,
     C_ADDRESS    VARCHAR(40) NOT NULL,
     C_NATIONKEY  INT NOT NULL,
     C_PHONE      CHAR(15) NOT NULL,
     C_ACCTBAL    DECIMAL(12, 2) NOT NULL,
     C_MKTSEGMENT CHAR(10) NOT NULL,
     C_COMMENT    VARCHAR(117) NOT NULL
  )
GO

CREATE TABLE supplier
  (
     S_SUPPKEY   BIGINT NOT NULL,
     S_NAME      CHAR(25) NOT NULL,
     S_ADDRESS   VARCHAR(40) NOT NULL,
     S_NATIONKEY INT NOT NULL,
     S_PHONE     CHAR(15) NOT NULL,
     S_ACCTBAL   DECIMAL(12, 2) NOT NULL,
     S_COMMENT   VARCHAR(101) NOT NULL
  )
GO

CREATE TABLE lineitem
  (
     L_ORDERKEY      BIGINT NOT NULL,
     L_PARTKEY       BIGINT NOT NULL,
     L_SUPPKEY       BIGINT NOT NULL,
     L_LINENUMBER    INT NOT NULL,
     L_QUANTITY      DECIMAL(12, 2) NOT NULL,
     L_EXTENDEDPRICE DECIMAL(12, 2) NOT NULL,
     L_DISCOUNT      DECIMAL(12, 2) NOT NULL,
     L_TAX           DECIMAL(12, 2) NOT NULL,
     L_RETURNFLAG    CHAR(1) NOT NULL,
     L_LINESTATUS    CHAR(1) NOT NULL,
     L_SHIPDATE      DATE NOT NULL,
     L_COMMITDATE    DATE NOT NULL,
     L_RECEIPTDATE   DATE NOT NULL,
     L_SHIPINSTRUCT  CHAR(25) NOT NULL,
     L_SHIPMODE      CHAR(10) NOT NULL,
     L_COMMENT       VARCHAR(44) NOT NULL
  )
GO

CREATE TABLE orders
  (
     O_ORDERKEY      BIGINT NOT NULL,
     O_CUSTKEY       BIGINT NOT NULL,
     O_ORDERSTATUS   CHAR(1) NOT NULL,
     O_TOTALPRICE    DECIMAL(12, 2) NOT NULL,
     O_ORDERDATE     DATE NOT NULL,
     O_ORDERPRIORITY CHAR(15) NOT NULL,
     O_CLERK         CHAR(15) NOT NULL,
     O_SHIPPRIORITY  INT NOT NULL,
     O_COMMENT       VARCHAR(79) NOT NULL
  )
GO

CREATE TABLE nation
  (
     N_NATIONKEY INT NOT NULL,
     N_NAME      CHAR(25) NOT NULL,
     N_REGIONKEY BIGINT NOT NULL,
     N_COMMENT   VARCHAR(152) NOT NULL
  )
GO

CREATE TABLE region
  (
     R_REGIONKEY BIGINT NOT NULL,
     R_NAME      CHAR(25) NOT NULL,
     R_COMMENT   VARCHAR(152) NOT NULL
  ) 
  GO