CREATE STATISTICS [MANUAL_C_ACCTBAL] ON [customer](C_ACCTBAL) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_C_ADDRESS] ON [customer](C_ADDRESS) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_C_COMMENT] ON [customer](C_COMMENT) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_C_CUSTKEY] ON [customer](C_CUSTKEY) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_C_MKTSEGMENT] ON [customer](C_MKTSEGMENT) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_C_NAME] ON [customer](C_NAME) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_C_NATIONKEY] ON [customer](C_NATIONKEY) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_C_PHONE] ON [customer](C_PHONE) WITH SAMPLE 100 PERCENT
 
GO
CREATE STATISTICS [MANUAL_L_COMMENT] ON [lineitem](L_COMMENT) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_COMMITDATE] ON [lineitem](L_COMMITDATE) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_DISCOUNT] ON [lineitem](L_DISCOUNT) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_EXTENDEDPRICE] ON [lineitem](L_EXTENDEDPRICE) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_LINENUMBER] ON [lineitem](L_LINENUMBER) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_LINESTATUS] ON [lineitem](L_LINESTATUS) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_ORDERKEY] ON [lineitem](L_ORDERKEY) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_PARTKEY] ON [lineitem](L_PARTKEY) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_QUANTITY] ON [lineitem](L_QUANTITY) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_RECEIPTDATE] ON [lineitem](L_RECEIPTDATE) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_RETURNFLAG] ON [lineitem](L_RETURNFLAG) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_SHIPDATE] ON [lineitem](L_SHIPDATE) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_SHIPINSTRUCT] ON [lineitem](L_SHIPINSTRUCT) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_SHIPMODE] ON [lineitem](L_SHIPMODE) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_SUPPKEY] ON [lineitem](L_SUPPKEY) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_TAX] ON [lineitem](L_TAX) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_N_COMMENT] ON [nation](N_COMMENT) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_N_NAME] ON [nation](N_NAME) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_N_NATIONKEY] ON [nation](N_NATIONKEY) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_N_REGIONKEY] ON [nation](N_REGIONKEY) WITH SAMPLE 100 PERCENT
GO
 
CREATE STATISTICS [MANUAL_O_CLERK] ON [orders](O_CLERK) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_O_COMMENT] ON [orders](O_COMMENT) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_O_CUSTKEY] ON [orders](O_CUSTKEY) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_O_ORDERDATE] ON [orders](O_ORDERDATE) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_O_ORDERKEY] ON [orders](O_ORDERKEY) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_O_ORDERPRIORITY] ON [orders](O_ORDERPRIORITY) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_O_ORDERSTATUS] ON [orders](O_ORDERSTATUS) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_O_SHIPPRIORITY] ON [orders](O_SHIPPRIORITY) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_O_TOTALPRICE] ON [orders](O_TOTALPRICE) WITH SAMPLE 100 PERCENT
GO
 
CREATE STATISTICS [MANUAL_P_BRAND] ON [part](P_BRAND) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_P_COMMENT] ON [part](P_COMMENT) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_P_CONTAINER] ON [part](P_CONTAINER) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_P_MFGR] ON [part](P_MFGR) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_P_NAME] ON [part](P_NAME) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_P_PARTKEY] ON [part](P_PARTKEY) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_P_RETAILPRICE] ON [part](P_RETAILPRICE) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_P_SIZE] ON [part](P_SIZE) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_P_TYPE] ON [part](P_TYPE) WITH SAMPLE 100 PERCENT
GO
 
CREATE STATISTICS [MANUAL_PS_AVAILQTY] ON [partsupp](PS_AVAILQTY) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_PS_COMMENT] ON [partsupp](PS_COMMENT) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_PS_PARTKEY] ON [partsupp](PS_PARTKEY) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_PS_SUPPKEY] ON [partsupp](PS_SUPPKEY) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_PS_SUPPLYCOST] ON [partsupp](PS_SUPPLYCOST) WITH SAMPLE 100 PERCENT
GO
 
CREATE STATISTICS [MANUAL_R_COMMENT] ON [region](R_COMMENT) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_R_NAME] ON [region](R_NAME) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_R_REGIONKEY] ON [region](R_REGIONKEY) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_S_ACCTBAL] ON [supplier](S_ACCTBAL) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_S_ADDRESS] ON [supplier](S_ADDRESS) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_S_COMMENT] ON [supplier](S_COMMENT) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_S_NAME] ON [supplier](S_NAME) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_S_NATIONKEY] ON [supplier](S_NATIONKEY) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_S_PHONE] ON [supplier](S_PHONE) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_S_SUPPKEY] ON [supplier](S_SUPPKEY) WITH SAMPLE 100 PERCENT
GO