-- Query 5
SELECT
  N_NAME,
  sum(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS revenue
FROM
  customer,
  orders,
  lineitem,
  supplier,
  nation,
  region
WHERE
  C_CUSTKEY = O_CUSTKEY
  AND L_ORDERKEY = O_ORDERKEY
  AND L_SUPPKEY = S_SUPPKEY
  AND C_NATIONKEY = S_NATIONKEY
  AND S_NATIONKEY = N_NATIONKEY
  AND N_REGIONKEY = R_REGIONKEY
  AND R_NAME = 'MIDDLE EAST'
  AND O_ORDERDATE >= '1997-01-01' -- [DATE]
  AND O_ORDERDATE < '1998-01-01'-- [DATE] + INTERVAL '1' YEAR
GROUP BY
  N_NAME
ORDER BY
  revenue DESC
OPTION (LABEL = 'TPCH-Q5')