-- Query 14
SELECT
  100.00 * sum(
    CASE WHEN P_TYPE LIKE 'PROMO%' THEN L_EXTENDEDPRICE * (1 - L_DISCOUNT) ELSE 0 END
  ) / sum(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS promo_revenue
FROM
  lineitem,
  part
WHERE
  L_PARTKEY = P_PARTKEY
	AND L_SHIPDATE	>= '1997-05-01'
	AND L_SHIPDATE	< dateadd(mm, 1,cast ('1997-05-01' as date))
OPTION (LABEL = 'TPCH-Q14')