-- Query 11
SELECT
  PS_PARTKEY,
  sum(PS_SUPPLYCOST * PS_AVAILQTY) AS value
FROM
  partsupp,
  supplier,
  nation
WHERE
  PS_SUPPKEY = S_SUPPKEY
  AND S_NATIONKEY = N_NATIONKEY
  AND N_NAME = 'GERMANY' -- [NATION]
GROUP BY
  PS_PARTKEY
HAVING
  sum(PS_SUPPLYCOST * PS_AVAILQTY) > (
    SELECT
      sum(PS_SUPPLYCOST * PS_AVAILQTY) * (0.0001 / {SCALE_FACTOR})-- [FRACTION]
    FROM
      partsupp,
      supplier,
      nation
    WHERE
      PS_SUPPKEY = S_SUPPKEY
      AND S_NATIONKEY = N_NATIONKEY
      AND N_NAME = 'GERMANY' -- [NATION]
  )
ORDER BY
  value DESC
OPTION (LABEL = 'TPCH-Q11')