-- Query 18
SELECT
  TOP (100) C_NAME,
  C_CUSTKEY,
  O_ORDERKEY,
  O_ORDERDATE,
  O_TOTALPRICE,
  sum(L_QUANTITY)
FROM
  customer,
  orders,
  lineitem
WHERE
  O_ORDERKEY IN (
    SELECT
      L_ORDERKEY
    FROM
      lineitem
    GROUP BY
      L_ORDERKEY
    HAVING
      sum(L_QUANTITY) > 253 -- [QUANTITY]
  )
  AND C_CUSTKEY = O_CUSTKEY
  AND O_ORDERKEY = L_ORDERKEY
GROUP BY
  C_NAME,
  C_CUSTKEY,
  O_ORDERKEY,
  O_ORDERDATE,
  O_TOTALPRICE
ORDER BY
  O_TOTALPRICE DESC,
  O_ORDERDATE
OPTION (LABEL = 'TPCH-Q18')