-- Query 12
SELECT
  L_SHIPMODE,
  sum(
    CASE WHEN O_ORDERPRIORITY = '1-URGENT'
    OR O_ORDERPRIORITY = '2-HIGH' THEN 1 ELSE 0 END
  ) AS high_line_count,
  sum(
    CASE WHEN O_ORDERPRIORITY <> '1-URGENT'
    AND O_ORDERPRIORITY <> '2-HIGH' THEN 1 ELSE 0 END
  ) AS low_line_count
FROM
  orders,
  lineitem
WHERE
  O_ORDERKEY = L_ORDERKEY
  AND L_SHIPMODE IN ('FOB', 'REG AIR') -- [SHIPMODE1], [SHIPTMODE2]
  AND L_COMMITDATE < L_RECEIPTDATE
  AND L_SHIPDATE < L_COMMITDATE
  AND L_RECEIPTDATE >= '1995-01-01'-- [DATE]
  AND L_RECEIPTDATE < '1996-01-01' -- [DATE] + interval '1' year
GROUP BY
  L_SHIPMODE
ORDER BY
  L_SHIPMODE
OPTION (LABEL = 'TPCH-Q12')